### ISSUE TITLE
BROADR demo

### ISSUE THREAD

**Issue by marton384** [njoy/NJOY21#105]
Hi Everyone,

I've been trying to plot uranium cross sections at 4-5 different temperatures with the BROADR module but I still struggle with the nuclear library coupling. I could not find any information in the manual how does the code find the right XS library file to tabulate the data, how does one define/edit the tape. In short the code cannot load the "tape" so the run fails. Where can I get the proper XS files (proper format)? I checked the tests downloaded/run with the install but they contain these "dummy tapes" made for the given case...Sorry for the troubles, I am new to the NJOY21! In advance thank you for the help!

**Comment by jlconlin** [comment]
@marton384 Can you share an input deck and initial ENDF file (i.e., tape20 )that you have created already? That would help us to help you.

**Comment by whaeck** [comment]
The tests provided with NJOY21 (and NJOY2016 as well) provide a large number of examples on how to use NJOY for various purposes. In your case, I would suggest looking at test 19 and 24, which give examples on processing an ACE library. Using RECONR and BROADR is a requirement to do that. You'll still need to download the ENDF files you wish to use and link to the ENDF file you wish to process. For instance, if your file is names 'u238.endf' and the first tape number used in the input is 20, than you should do this:
ln -s u238.endf tape20
or:
cp u238.endf tape20

I personally prefer the first solution, but that's a matter of taste.
