### ISSUE TITLE
Trouble with make NJOY21 in Cygwin64 Virtual Linux Environment, Windows 10 OS

### ISSUE THREAD

**Issue by Kutyreff** [njoy/NJOY21#109]
Hello,

When trying to make NJOY21 (following the installation guide online), the operation failed with errors:

[ 27%] Building Fortran object subprojects/njoy/CMakeFiles/njoy.dir/src/endf.f90.o
f951: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[2]: *** [subprojects/njoy/CMakeFiles/njoy.dir/build.make:206: subprojects/njoy/CMakeFiles/njoy.dir/src/endf.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:350: subprojects/njoy/CMakeFiles/njoy.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

I reran make VERBOSE=1 to try to understand more about what was going wrong, and got this:

[ 22%] Building Fortran object subprojects/njoy/CMakeFiles/njoy.dir/src/endf.f90.o
cd /home/ckuty/NJOY/NJOY21/bin/subprojects/njoy && /usr/bin/gfortran.exe -Dnjoy_EXPORTS -I/home/ckuty/NJOY/NJOY21/bin/fortran_modules  -J../../fortran_modules   -c /home/ckuty/NJOY/NJOY21/subprojects/njoy/src/endf.f90 -o CMakeFiles/njoy.dir/src/endf.f90.o
f951: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[2]: *** [subprojects/njoy/CMakeFiles/njoy.dir/build.make:206: subprojects/njoy/CMakeFiles/njoy.dir/src/endf.f90.o] Error 1
make[2]: Leaving directory '/home/ckuty/NJOY/NJOY21/bin'
make[1]: *** [CMakeFiles/Makefile2:350: subprojects/njoy/CMakeFiles/njoy.dir/all] Error 2
make[1]: Leaving directory '/home/ckuty/NJOY/NJOY21/bin'
make: *** [Makefile:163: all] Error 2

Any and all help is appreciated. Please and thank you.

Best,

CK

**Comment by nathangibson14** [comment]
Hi CK,

Thanks for reaching out.  I haven't seen issues like this before, but I also don't have much experience on using NJOY on Windows either.

This looks like a compiler bug.  What version of GCC are you using?  Do you have access to another compiler or another version on your system?

Thanks,
Nathan

**Comment by Kutyreff** [comment]
Hello Nathan,

Thanks for getting back to me. And sorry for my slow response. I tried updating GCC and Cygwin to solve the issue, and indeed I am no longer getting the seg fault error. However, I am now faced with a new problem when compiling:

[ 84%] Building CXX object CMakeFiles/njoy21.dir/src/main.cpp.o
/usr/lib/gcc/x86_64-pc-cygwin/9.3.0/../../../../x86_64-pc-cygwin/bin/as: CMakeFiles/njoy21.dir/src/main.cpp.o: too many sections (58183)
/tmp/cc0pEF50.s: Assembler messages:
/tmp/cc0pEF50.s: Fatal error: can't write 56 bytes to section .text of CMakeFiles/njoy21.dir/src/main.cpp.o: 'file too big'
/usr/lib/gcc/x86_64-pc-cygwin/9.3.0/../../../../x86_64-pc-cygwin/bin/as: CMakeFiles/njoy21.dir/src/main.cpp.o: too many sections (58183)
/tmp/cc0pEF50.s: Fatal error: can't close CMakeFiles/njoy21.dir/src/main.cpp.o: file too big
make[2]: *** [CMakeFiles/njoy21.dir/build.make:63: CMakeFiles/njoy21.dir/src/main.cpp.o] Error 1
make[2]: Leaving directory '/home/ckuty/NJOY/NJOY21/bin'
make[1]: *** [CMakeFiles/Makefile2:115: CMakeFiles/njoy21.dir/all] Error 2
make[1]: Leaving directory '/home/ckuty/NJOY/NJOY21/bin'
make: *** [Makefile:163: all] Error 2

This is with the updated version of GCC (9.3.0-2), but I can try previous versions (9.2 or 7.4). 

Again, grateful for any and all assistance you are willing to offer.

Cheers,

CK

**Comment by Kutyreff** [comment]
Hello again Nathan,

Just to follow up, I seem to have successfully installed NJOY2016 in this environment (0 of 55 tests failed in the make test stage). I am not sure if this information is diagnostically helpful, but I thought I would share it anyway.


Cheers,

CK

**Comment by nathangibson14** [comment]
Thanks for the information.  You seem to be getting the same issue as #110, which just came in last night, so it's good to know this is a consistent problem in Cygwin.  Using NJOY2016 was my suggested workaround, so you already found that solution.

I'll try to get a Windows machine up and running to see if I can fix the compile flags leading to that problem.

Thanks,
Nathan

**Comment by RokShox** [comment]
Yes I solved this problem. See my updates to #110.

**Comment by Kutyreff** [comment]
Thanks everybody. I am less savvy than the rest, so I'll stick with NJOY2016 until the Cygwin fixes get implemented. I appreciate all the help!
