### ISSUE TITLE
subprojects error

### ISSUE THREAD

**Issue by Tread84** [njoy/NJOY21#113]
When I run the following command: ../metaconfigure/fetch_subprojects.py ../1.1.0-NJOY21.json

I get the output on my screen:

Updating to master branch...

However, when I go to make NJOY21 directory there are no subprojects that have been created.. Any help would be greatly appreciated.

**Comment by jlconlin** [comment]
I suspect you are running that command from the `bin` directory. Correct? If so, you won't see the `subprojects` directory there. The `subprojects` directory will be in the `njoy21` directory as a sister directory to `metaconfigure`. Can you check to see if it's there?

**Comment by jlconlin** [comment]
I need to correct what I said. The command:

```console
./metaconfigure/fetch_subprojects.py ../1.1.0-NJOY21.json
```
Needs to be executed from the top-level directory of NJOY21. If you execute that command anywhere else, it won't work.

**Comment by Tread84** [comment]
So this is the error, that is received upon running that command:

Traceback (most recent call last):
  File "./metaconfigure/fetch_subprojects.py", line 101, in <module>
    with open ( sys.argv[1], "r" ) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '../1.1.0-NJOY21.json'

**Comment by jlconlin** [comment]
So I think you are doing this from the wrong place. Let's start fresh. Delete the repository you have cloned and do the following (taken directly from http://www.njoy21.io/Build/index.html):

```console
# Download the source code
git clone https://github.com/njoy/NJOY21.git

# Get the desired version of NJOY21 (1.1.0 in this example)
cd NJOY21
wget https://raw.githubusercontent.com/njoy/signatures/master/NJOY21/1.1.0-NJOY21.json
./metaconfigure/fetch_subprojects.py 1.1.0-NJOY21.json
```
