### ISSUE TITLE
tape20 and input files for test2

### ISSUE THREAD

**Issue by negatron1** [njoy/NJOY21#165]
Hi everyone, hope everything s going well!
I am new to NJOY environment, just downloded code, and made tests. Then, I wanted to figure out which files are used when the input files are executed. I opened the tape20 and input files in test2. I faced pendf tape for **"pu-238 from endf/b-iv tape 404"** in inp file while in tape20, **9.22340+** appeared, for that reason ı searched for endf files on the internet and visited **https://t2.lanl.gov/nis/data/endf/endfiv.html** in which tape20 file for test2 matched with U-234 despite defining as pu-238 in test2 input file.
My questions are that;
Aformentioned above, ı am new to njoy21 so "t2.lanl.gov" is right place to download endf tape files?
If it is, how can I find endf/b-VIII data? Because that website (https://t2.lanl.gov/nis/data/endf/) includes data files up to endf/b-VII.1
thanks in advance, hearing soon :)

**Comment by nathangibson14** [comment]
Hi @negatron1 , the T-2 website is quite old and out of date, as you are already observing!  I still recommend some of the NJOY information on that site if you can find it, as much of it is still relevant, even if not perfectly conforming to our newest versions' input files.

For ENDF files, you should get them from the NNDC at Brookhaven: https://www.nndc.bnl.gov/endf/

Let us know if you need more help with NJOY.
