### ISSUE TITLE
Read COVR matrices

### ISSUE THREAD

**Issue by rolekst095** [njoy/NJOY21#173]
Hello

NJOY has powerful modules to produce and plot uncertainties matrices of multigroup cross sections (ERRORR and COVR).

But for now the question: is there a way to parse that data in numpy arrays or any other formats so data can be used for generating 
cross sections samples from covariance matrices?

Is there a convenient way to read this matrices in python for example? 

Best regards

**Comment by osama19976** [comment]
Hi, 
I am having hard time  to read and parse COVR output , I see that you posted this query last year , I hope you found a way to do that , and if you did , I would be grateful to help me out with this issue

**Comment by rolekst095** [comment]
Hello
This is a rather old problem and I could forget all the nuances, but I will describe what I found

I solved the problem by parsing the output file using this snippet

```
import numpy as np

def read_covr(output_name, mt1, mt2, mat):
    f = open(output_name)
    lines = f.readlines()
    covr = f"relative covariance ( mt{mt1:3d} , ig , {mat}" + f"mt{mt2:3d} , igp )"
    covr_arr = np.zeros((69, 69))

    for i in range(len(lines)):
        if covr in lines[i]:
            k = i + 4
            while (lines[k] != "\n" and ("s" not in lines[k])):
                floatL = list(map(float, lines[k].split()))
                covr_arr[int(floatL[0])-1, int(floatL[1]) -
                        1:int(floatL[1])-1 + len(floatL) - 2] = floatL[2:]
                k += 1
    # assert np.any(covr_arr)
    return covr_arr
```
First arg is njoy output file, 

Second and third args is reaction indexes for parsing correlation

Forth arg is made for parsing correlation among different nuclide ie between U235 and U238 in this case it is `"mat" + mat_id + "/"
`in other cases this arg is empty string `""`

For example call
`read_covr(out_name, 1, 1, "")`
