### ISSUE TITLE
Error stop with commented module call

### ISSUE THREAD

**Issue by kernie** [njoy/NJOY21#3]
Hi there,

when calling a module and having something like this:

moder / CALL MODER TO CONVERT ASCII  - BINARY

NJOY21 will stop with:

[error] Unrecognized routine label on line 1
[info] Requested routine: MODER / ALL MODER TO CONVERT ASCII  - BINARY
[info] Error while running NJOY21

Earlier versions didn't have problems ...

Best regards,
Maarten

**Comment by apmccartney** [comment]
Good catch. I'll create an issue to address this.

**Comment by apmccartney** [comment]
I apologie for the delay and thank you for the reproducible example and reference output.

**Comment by apmccartney** [comment]
The correction has been merged into master. Thank you again for your feedback.
