### ISSUE TITLE
HEATR::Card1::Nout::Nout.test.cpp references THERMR not HEATR

### ISSUE THREAD

**Issue by ameliajo** [njoy/NJOY21#47]

**Comment by apmccartney** [comment]
Good catch. On it.

**Comment by apmccartney** [comment]
Whoops. Looks like you've started already.

**Comment by jlconlin** [comment]
I was wondering how long @AmeliaJo could stay away from the NJOY life.

**Comment by jlconlin** [comment]
Moved to [lipservice](https://github.com/njoy/lipservice/issues/3).
