### ISSUE TITLE
Installation and run

### ISSUE THREAD

**Issue by nasim-arcturus** [njoy/NJOY21#85]
Done every step mentioned "Obtaining and Installing NJOY" page. All test passed.
While using command like `njoy21 --version` or any njoy21 command, getting following errors:

`njoy21: error while loading shared libraries: libnjoy_c_bindings.so: cannot open shared object file: No such file or directory`

**Comment by Snomstor** [comment]
> 
> 
> Done every step mentioned "Obtaining and Installing NJOY" page. All test passed.
> While using command like `njoy21 --version` or any njoy21 command, getting following errors:
> 
> `njoy21: error while loading shared libraries: libnjoy_c_bindings.so: cannot open shared object file: No such file or directory`

Hello! How did you solve this problem?

**Comment by whaeck** [comment]
The error indicates that you probably moved the executable without the dynamic library that's associated to it.

You can also compile the code to produce a static executable, you can do this by adding some additional cmake commands:
```
cmake -D static_libraries=True -D static_njoy=True -D CMAKE_EXE_LINKER_FLAGS="-static" ../
```
That should avoid the issue entirely.

**Comment by Snomstor** [comment]
> 
> 
> The error indicates that you probably moved the executable without the dynamic library that's associated to it.
> 
> You can also compile the code to produce a static executable, you can do this by adding some additional cmake commands:
> 
> ```
> cmake -D static_libraries=True -D static_njoy=True -D CMAKE_EXE_LINKER_FLAGS="-static" ../
> ```
> 
> That should avoid the issue entirely.

Thanks) I'll try to use this command too. For now, I have found the next solution: I have just  copied the file libnjoy_c_bindings.so from /bin/subprojects/njoy_c_bindings to /usr/lib.
