### ISSUE TITLE
Build issue on macOS

### ISSUE THREAD

**Issue by brown170** [njoy/NJOY21#88]
I could not get NJOY21 to build without adding the "-Wno-maybe-uninitialized" flag to the set of common Darwin build flags.  This is what my line 132 of CMakeList.txt looks like:

set( njoy21_GNU_Darwin_common_flags "-Wall" "-Wextra" "-Wpedantic" "-Wno-maybe-uninitialized" "-std=c++14" )

This same flag is used by default for Linux builds.

**Comment by jlconlin** [comment]
What compiler versions did you use?

**Comment by brown170** [comment]
gcc (MacPorts gcc8 8.3.0_4) 8.3.0

The command line switch "-Wno-maybe-uninitialized" is identical to that on Linux.

**Comment by jlconlin** [comment]
We build regularly on Mac with gcc, but we don't use MacPorts. It seems unlikely that MacPorts is the issue. Will have to do some additional checking.

**Comment by brown170** [comment]
Might be useful to add a discussion of supported compilers on the NJOY21 website...

**Comment by jlconlin** [comment]
We do state what minimum compilers are required, but often state something like "clang 3.7+". Perhaps using the "+" is not precise enough. The documentation could certainly be improved.

**Comment by brownjm1968** [comment]
I just ran into the same issue and solved with the same flag as Dave when building with gcc 9.2 (homebrew installed)

**Comment by jlconlin** [comment]
@brownjm1968 Can you tell me the commands that you used to compile NJOY21

**Comment by brownjm1968** [comment]
```
$ git clone https://github.com/njoy/NJOY21.git
$ cd NJOY21/
$ curl -O https://raw.githubusercontent.com/njoy/signatures/master/NJOY21/1.0.1-NJOY21.json
$ ./metaconfigure/fetch_subprojects.py 1.0.1-NJOY21.json 
$ mkdir bin
$ cd bin/
$ vim ../CMakeLists.txt 
$ cmake -D fetched_subprojects=true -D CMAKE_BUILD_TYPE=release ../
$ make -j7
$ make -j7 test
```
